[package]
name = "device_status"
version = "1.0.0"
edition = "2021"
build = "build.rs"

[[bin]]
name = "device_status"
path = "src/main.rs"

[build-dependencies]
winresource = "0.1"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serialport = "4"

wmi = "0.14"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
